### ISSUE TITLE
报BUG

### ISSUE THREAD

**Issue by MJDDH** [tencent-ailab/RLogist#1]
运行python main.py --source DATA_DIRECTORY --label_list LABEL_LIST.csv之后，报错如下：
    run_name = f"RLogist__{args.exp_name}__{args.seed}__{int(time.time())}"
AttributeError: 'Namespace' object has no attribute 'exp_name'
通过parser.add_argument把exp_name加上之后，继续运行报错如下：
[make_env(args.env_id, args.seed + i, i, run_name) for i in range(args.num_envs)]
TypeError: make_env() missing 1 required positional argument: 'run_name'
环境都和里面要求的一模一样，真是百思不得其解，求大佬指点迷津，万分感谢！

**Comment by irsLu** [comment]
我也是 解决了吗
