### ISSUE TITLE
requirements.txt文件里面的有些版本存在冲突

### ISSUE THREAD

**Issue by MJDDH** [tencent-ailab/RLogist#2]
requirements.txt文件里面的有些版本存在冲突

**Comment by BoxuanZhao** [comment]
We auto-generated requirements.txt using pipreqs. Could you elaborate on which ones are in conflict?

**Comment by MJDDH** [comment]
运行的时候提示说是torchvision~=0.12.0不支持torch1.12.0,让换成torch1.11.0

**Comment by BoxuanZhao** [comment]
正常来说按照torch官网的安装命令，torch torchvision cuda的版本都是对应的，应该不用特意修改，我们就是这样配的环境。
